-- DUMP FINAL — ATT V GERES
-- Período: 27/08/2026 a 01/09/2026
-- Base final: 28 registros
-- Alterações: Guarda Municipal de Trânsito -> AMSTT; Polícia Rodoviária Federal excluída.

DROP TABLE IF EXISTS att_v_geres_2026_08_27_2026_09_01;
CREATE TABLE att_v_geres_2026_08_27_2026_09_01 (
    "ID_Simulado" INTEGER,
    "Municipio_Notificacao" TEXT,
    "Instituicao_Notificadora" TEXT,
    "Endereco_Sinistro" TEXT,
    "Veiculo_Usuario" TEXT,
    "Sinistro_Com_Vitimas" TEXT,
    "Perfil_Vitimas" TEXT,
    "Equipamento_Seguranca" TEXT,
    "Latitude" DOUBLE PRECISION,
    "Longitude" DOUBLE PRECISION,
    "Registro_No_Local" TEXT,
    "Data_Notificacao" DATE,
    "Hora_Notificacao" TIME,
    "Tempo_Gasto_Notificacao_min" INTEGER
);

INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1289, 'Garanhuns', 'AMSTT', 'BR-423, Km 93 - Heliópolis', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -8.878109, -36.47662, 'SIM', '2026-08-28', '18:42', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1294, 'Bom Conselho', 'AMSTT', 'Praça Dom Pedro II, 126 - Centro', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -9.1714, -36.668, 'SIM', '2026-08-28', '19:56', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1301, 'Garanhuns', 'AMSTT', 'Rua Quinze de Novembro, 219 - Santo Antônio', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.8884569, -36.4916065, 'SIM', '2026-08-30', '10:27', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1309, 'Garanhuns', 'AMSTT', 'BR-423, Km 98 - Magano', 'Automóvel', 'SIM', 'MODERADA', 'CINTO DE SEGURANÇA', -8.89, -36.493, 'SIM', '2026-08-31', '16:02', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1284, 'Garanhuns', 'Polícia Militar', 'Av. Rui Barbosa, 776 - Heliópolis', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.88153, -36.47582, 'SIM', '2026-08-27', '20:14', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1290, 'Caetés', 'Polícia Militar', 'Praça Rafael Brasil Pereira, s/n - Centro', 'Motocicleta', 'SIM', 'SEM GRAVIDADE', 'CAPACETE', -8.77288, -36.62558, 'SIM', '2026-08-28', '11:08', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1292, 'Lajedo', 'Polícia Militar', 'Av. Gov. Agamenon Magalhães, 160 - Centro', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.6602, -36.3223, 'SIM', '2026-08-28', '22:31', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1295, 'Garanhuns', 'Polícia Militar', 'Av. Bom Pastor, s/n - Boa Vista', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.90557, -36.49495, 'SIM', '2026-08-29', '20:27', 6);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1303, 'Canhotinho', 'Polícia Militar', 'Rua 13 de Maio, s/n - Centro', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.883, -36.194, 'SIM', '2026-08-30', '14:46', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1300, 'São João', 'Polícia Militar', 'Av. Joaquim Pereira dos Santos, s/n - Centro', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.8718247167, -36.36574735, 'SIM', '2026-08-30', '19:33', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1307, 'Garanhuns', 'Polícia Militar', 'Av. Caruaru, 1609 - Heliópolis', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.8818269, -36.4868973, 'SIM', '2026-08-31', '18:17', 6);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1310, 'Lajedo', 'Polícia Militar', 'Av. Gov. Agamenon Magalhães, 160 - Centro', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.6602, -36.3223, 'SIM', '2026-08-31', '22:57', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1315, 'Garanhuns', 'Polícia Militar', 'Av. Duque de Caxias, 433 - Heliópolis', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.88497, -36.46621, 'SIM', '2026-09-01', '06:49', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1285, 'Lajedo', 'SAMU', 'Rua Duque de Caxias, 746 - Centro', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.6602, -36.3223, 'SIM', '2026-08-27', '09:36', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1291, 'Garanhuns', 'SAMU', 'BR-423, Km 98 - Magano', 'Automóvel', 'SIM', 'MODERADA', 'CINTO DE SEGURANÇA', -8.89, -36.493, 'SIM', '2026-08-28', '21:05', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1296, 'Garanhuns', 'SAMU', 'Av. Euclides Dourado, 277 - Heliópolis', 'Caminhonete', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.88443, -36.47751, 'SIM', '2026-08-29', '07:42', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1302, 'Garanhuns', 'SAMU', 'Av. Rui Barbosa, 776 - Heliópolis', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -8.88153, -36.47582, 'SIM', '2026-08-30', '20:51', 6);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1308, 'Garanhuns', 'SAMU', 'BR-423, Km 93 - Heliópolis', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.878109, -36.47662, 'SIM', '2026-08-31', '21:46', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1314, 'Garanhuns', 'SAMU', 'Av. Duque de Caxias, 286 - Heliópolis', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.88497, -36.46621, 'SIM', '2026-09-01', '22:06', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1286, 'Garanhuns', 'Corpo de Bombeiros', 'Av. Rui Barbosa, 400 - Heliópolis', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -8.88555, -36.48472, 'SIM', '2026-08-27', '22:48', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1293, 'Garanhuns', 'Corpo de Bombeiros', 'Av. Santo Antônio, 382 - Santo Antônio', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.8909, -36.4954, 'SIM', '2026-08-28', '16:18', 5);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1299, 'Garanhuns', 'Corpo de Bombeiros', 'Av. Duque de Caxias, 433 - Heliópolis', 'Bicicleta', 'SIM', 'SEM GRAVIDADE', 'CAPACETE', -8.88497, -36.46621, 'SIM', '2026-08-29', '23:06', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1304, 'Lajedo', 'Corpo de Bombeiros', 'Rua Duque de Caxias, 746 - Centro', 'Motocicleta', 'SIM', 'GRAVE', 'CAPACETE', -8.6602, -36.3223, 'SIM', '2026-08-30', '22:19', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1311, 'Garanhuns', 'Corpo de Bombeiros', 'Av. Santo Antônio, 382 - Santo Antônio', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.8909, -36.4954, 'SIM', '2026-09-01', '12:23', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1287, 'Canhotinho', 'Polícia Civil', 'Rua 13 de Maio, s/n - Centro', 'Automóvel', 'SIM', 'SEM GRAVIDADE', 'CINTO DE SEGURANÇA', -8.883, -36.194, 'SIM', '2026-08-27', '15:21', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1298, 'Garanhuns', 'Polícia Civil', 'Av. Duque de Caxias, 286 - Heliópolis', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -8.88497, -36.46621, 'SIM', '2026-08-29', '13:14', 3);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1306, 'Jupi', 'Polícia Civil', 'Praça Pedro Paulo Filho, 4 - Centro', 'Motocicleta', 'SIM', 'MODERADA', 'CAPACETE', -8.7103, -36.3956, 'SIM', '2026-08-31', '08:55', 4);
INSERT INTO att_v_geres_2026_08_27_2026_09_01 ("ID_Simulado", "Municipio_Notificacao", "Instituicao_Notificadora", "Endereco_Sinistro", "Veiculo_Usuario", "Sinistro_Com_Vitimas", "Perfil_Vitimas", "Equipamento_Seguranca", "Latitude", "Longitude", "Registro_No_Local", "Data_Notificacao", "Hora_Notificacao", "Tempo_Gasto_Notificacao_min") VALUES (1313, 'Garanhuns', 'Polícia Civil', 'Av. Euclides Dourado, 277 - Heliópolis', 'Caminhonete', 'SIM', 'MODERADA', 'CINTO DE SEGURANÇA', -8.88443, -36.47751, 'SIM', '2026-09-01', '17:12', 4);
